[package]
name = "lan_clipboard"
version = "0.1.0"
authors = ["Kyle Clemens <lan_clipboard@kyleclemens.com>"]
build = "build.rs"

[dependencies]
protobuf = "1.4"
integer-encoding = "1.0"

[build-dependencies]
protoc-rust = "1.4"
